name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-go@v3
          with:
            go-version: ^1.19
        - uses: actions/checkout@v3
        - name: go test
          run: go test `go list ./... | grep -v github.com/isso-719/hoppii-api/pkg/user`